### ISSUE TITLE
The link for Shoes Dataset is broken

### ISSUE THREAD

**Issue by ChenAnno** [naver/artemis#2]
Thank you for your great work in ICLR 2022!
However, the link for Shoes Dataset is broken:http://tamaraberg.com/attributesDataset/index.html
Could you please provide the download link for the images of Shoes Dataset?

Great thanks!

**Comment by g-delmas** [comment]
Hi,

Thank you for your interest.

This is indeed the correct link to download the images (the same link is provided on [this page](https://github.com/XiaoxiaoGuo/fashion-retrieval/tree/master/dataset)).
Unfortunately, we don't own these images, so we are not allowed to redistribute them. We contacted [the author](http://tamaraberg.com/) about the broken link. We will keep you updated!

**Comment by ChenAnno** [comment]
> Hi,
> 
> Thank you for your interest.
> 
> This is indeed the correct link to download the images (the same link is provided on [this page](https://github.com/XiaoxiaoGuo/fashion-retrieval/tree/master/dataset)). Unfortunately, we don't own these images, so we are not allowed to redistribute them. We contacted [the author](http://tamaraberg.com/) about the broken link. We will keep you updated!

Thank you so much for your kind reply!

**Comment by ChenAnno** [comment]
Hi, NAVER team,


Thank you so much for your kind reply!


Best wishes,
Anno Chen
Peking University




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "naver/artemis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月31日(星期一) 晚上9:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [naver/artemis] The link for Shoes Dataset is broken (Issue #2)





 
Hi,
 
Thank you for your interest.
 
This is indeed the correct link to download the images (the same link is provided on this page).
 Unfortunately, we don't own these images, so we are not allowed to redistribute them. We contacted the author about the broken link. We will keep you updated!
