### ISSUE TITLE
in generate_heatmaps.py's line 154, data_id and 'formated_caption, ref_identifier, trg_identifier' doesn't seem to match

### ISSUE THREAD

**Issue by 1124146862** [naver/artemis#3]
# Get data
		img_src, txt, txt_len, img_trg, ret_caps, data_id = next(data_loader_iterator)

		example_number = data_id[0] # batch size is 1

		if (studied_indices is None) or (example_number in studied_indices):

			# Process data
			generate_heatmap_from_single_data(args, model, img_src, txt, txt_len,
												img_trg, example_number)

			# store image identifiers & caption
			formated_caption, ref_identifier, trg_identifier = data_loader.dataset.get_triplet_info(example_number)

in generate_heatmaps.py's line 154, data_id and 'formated_caption, ref_identifier, trg_identifier' doesn't seem to match.

**Comment by g-delmas** [comment]
Hello!
Thank you for pointing that out. We just pushed a fix. Code changed just a little in dataset_fashionIQ.py:
https://github.com/naver/artemis/blob/f36f7793c55f24e905982f01e88775250e435596/dataset_fashionIQ.py#L125-L135

**Comment by 1124146862** [comment]
> Hello! Thank you for pointing that out. We just pushed a fix. Code changed just a little in dataset_fashionIQ.py:
> 
> https://github.com/naver/artemis/blob/f36f7793c55f24e905982f01e88775250e435596/dataset_fashionIQ.py#L125-L135

thank you for your reply
