### ISSUE TITLE
Problems about Fashion200k dataset

### ISSUE THREAD

**Issue by JWargrave** [naver/artemis#4]
Hi, there.

Thank you for the great work!

According to [fashion200k repo](https://github.com/xthan/fashion-200k#dataset), there are two versions of Fashion200k pictures, namely `cropped detected images` and `original images`, which one do you use in your implementation?

**Comment by rafael-sampaio-de-rezende** [comment]
Hello.

Thank you for your interest in our work!

We followed the experiments described in [TIRG](https://github.com/google/tirg#fashion200k-dataset), so we used the cropped images available to download at the [fashion200k repo](https://github.com/xthan/fashion-200k#dataset) under the name of `women.tar.gz`. We notice that, according to the fashion200k authors, the original images are only available via URLs that are many years old. So there will likely be many missing original images.
